/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import model.Pedido;
import model.Produto;
import model.Funcionario;
import dao.PedidoDAO;
import dao.ProdutoDAO;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Cliente;
import model.RelatorioPorId;

/**
 *
 * @author maria
 */
public class TelaRelatorioPorId extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRelatorioPorId.class.getName());

    /**
     * Creates new form TelaRelatorioPorId
     */
    private List<RelatorioPorId> tabela = new ArrayList<>();
    private PedidoDAO pedidoDAO = new PedidoDAO();
    public TelaRelatorioPorId() {
        initComponents();
        carregarPedidos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblID = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRelatorio = new javax.swing.JTable();
        btnGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblID.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblID);

        tblRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblRelatorio);

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnGerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(btnGerar)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        // TODO add your handling code here:
        int linha = tblID.getSelectedRow();
        if (linha >= 0) {
            int id = Integer.parseInt(tblID.getValueAt(linha, 0).toString());
            RelatorioPorId pedido = pedidoDAO.buscarPorId(id);
            String forma_pagamento = pedido.getForma_pagamento();
            LocalDateTime data_de_venda = pedido.getData_de_venda();
            String nome_funcionario = pedido.getNome_funcionario();
            String nome_cliente = pedido.getNome_cliente();
            BigDecimal preco = pedido.getPreco();
            LocalDateTime data_de_confirmacao = pedido.getData_de_confirmacao();

            tabela.add(new RelatorioPorId(forma_pagamento, data_de_venda, nome_funcionario, nome_cliente, preco, data_de_confirmacao));
            atualizarTabela();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um pedido.");
        }
    }//GEN-LAST:event_btnGerarActionPerformed

    private void carregarPedidos() {
    List<Pedido> lista = pedidoDAO.listar();

    String[] colunas = {"ID", "Data de venda", "Status"};
    Object[][] dados = new Object[lista.size()][3];

    for (int i = 0; i < lista.size(); i++) {
        Pedido p = lista.get(i);
        dados[i][0] = p.getIdPedido();
        dados[i][1] = p.getDataDeVenda();
        dados[i][2] = p.getStatus();
    }

    tblID.setModel(new javax.swing.table.DefaultTableModel(dados, colunas));
}
    private void atualizarTabela() {
    String[] colunas = {"Forma de Pagamento", "Data da Venda", "Nome do funcionario", "Nome do Cliente", "Preço", "Data da Confirmação"};
    Object[][] dados = new Object[tabela.size()][6];

    for (int i = 0; i < tabela.size(); i++) {
        RelatorioPorId item = tabela.get(i);
        dados[i][0] = item.getForma_pagamento();
        dados[i][1] = item.getData_de_venda();
        dados[i][2] = item.getNome_funcionario();
        dados[i][3] = item.getNome_cliente();
        dados[i][4] = item.getPreco();
        dados[i][5] = item.getData_de_confirmacao();
    }

    tblRelatorio.setModel(new javax.swing.table.DefaultTableModel(dados, colunas));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblID;
    private javax.swing.JTable tblRelatorio;
    // End of variables declaration//GEN-END:variables
}
